#!/bin/sh
# Usage: sclVMEC ext sclfactor btorfactor
# *** Still being improved, not finished yet ***

# Scale all rbc, zbs fourier coeffs in vmec by same factor
# This scales vmec shape by a scale

if [ "$1" ]
then
  ext=$1
else
  echo 'Enter VMEC extension'
  read ext  
fi
  inf=input.$ext

if [ "$2" ]
then
  f=$2
else
  echo 'Enter new Rcntr'
  read f
fi

if [ "$3" ]
then
  b=$3
else
  echo 'Enter new Btor'
  read b
fi

# Calculate scaling factors for R and phiedge

echo "! input.$ext rzmn coeffs scaled by $f :"

# Extract RBC, ZBS values from vmec input file and multiply by f into tmpR, tmpZ
grep -i "RBC(" $inf | grep -i "ZBS(" | awk -F= '{print $2}' | awk '{print $1}' | sed 's/,//' | awk '{$1=$1*'$f';printf "%20.12e\n", $1}' > tmpR
grep -i "RBC(" $inf | grep -i "ZBS(" | awk -F= '{print $3}' | awk '{print $1}' | sed 's/,//' | awk '{$1=$1*'$f';printf "%20.12e\n", $1}' > tmpZ

# Reconstruct rzmn table
grep -i "RBC(" $inf | grep -i "ZBS(" | awk -F= '{print " ",$1,"="}' > tmpRR
grep -i "RBC(" $inf | grep -i "ZBS(" | awk -F= '{print $2}' | awk '{print $2,$3,$4,"="}' > tmpZZ
paste tmpRR tmpR tmpZZ tmpZ

rm -f tmpRR tmpR tmpZZ tmpZ

# Remove spaces before =
# Multiply column 2 & 4 by $f
# grep "RBC(" $inf | grep "ZBS(" | sed 's/ *=/=/g' | sed 's/,//' | awk '{$2=$2*'$f';$4=$4*'$f';printf "%12s %20.12e %12s %20.12e\n", $1, $2, $3, $4}'


# Multiply RAXIS & ZAXIS by same factor f
grep -i "raxis" $inf | grep -i "zaxis" | sed 's/ *=/=/g' | sed 's/,//' | awk '{$2=$2*'$f';$4=$4*'$f';printf "%12s %20.12e %12s %20.12e\n", $1, $2, $3, $4}'

# Replace phiedge by phiedge f^2 * bTor_ratio
grep -i "PHIEDGE" $inf | awk -F= '{$2=$2*'$b'*'$f'*'$f';printf "%10s %20.12e\n", "PHIEDGE=", $2}'

# Replace the rzmn and raxis in input file with tmp
# for now do this by hand
#
